#ifndef STRATEGEMS_H
#define STRATEGEMS_H

#define REINFORCE "wsdaw"
#define SOS "wsdw"
#define RESUPPLY "sswd"
#define HELLBOMB "swaswdsw"
#define EAGLE_REARM "wwawd"
#define SEAF_ARTILLERY "dwws"

#define JUMP_PACK "swwsw"
#define SUPPLY_PACK "saswws"
#define LAS_GUARD_DOG "swawdd"
#define BALLISTIC_SHIELD "sasswa"
#define SHIELD_PACK "swadad"
#define AR23_GUARD_DOG "swawds"

#define MG43 "saswd"
#define AMR "sadws"
#define STALWART "saswwa"
#define EAT17 "ssawd"
#define RECOILLESS_RIFLE "sadda"
#define FLAMETHROWER "sawsw"
#define AUTOCANNON "saswwd"
#define HMG "sawss"
#define RAILGUN "sdswad"
#define LASER_CANNON "saswa"
#define ARC_THROWER "sdswaa"
#define QUASAR_CANNON "sswad"

#define EXOSUIT "asdwass"

#define HMG_EMPLACEMENT "swadda"
#define SHIELD_RELAY "ssadad"
#define TESLA_TOWER "swdwad"
#define AP_MINEFIELD "sawd"
#define INCENDIARY_MINEFIELD "saas"
#define MG_SENTRY "swddw"
#define GATLING_SENTRY "swda"
#define MORTAR_SENTRY "swdds"
#define AUTOCANNON_SENTRY "swdwaw"
#define ROCKET_SENTRY "swdda"
#define EMS_MORTAR_SENTRY "swdsd"

#define ORBITAL_GATLING_BARRAGE "dsaww"
#define ORBITAL_AIRBURST "ddd"
#define ORBITAL_120MM "ddsads"
#define ORBITAL_380MM "dswwass"
#define ORBITAL_WALKING_BARRAGE "dsdsds"
#define ORBITAL_LASER "dswds"
#define ORBITAL_RAILCANNON "dwssd"
#define ORBITAL_PRECISION_STRIKE "ddw"
#define ORBITAL_GAS "ddsd"
#define ORBITAL_EMS "ddas"
#define ORBITAL_SMOKE "ddsw"

#define STRAFING_RUN "wdd"
#define AIRSTRIKE "wdsd"
#define CLUSTER_BOMB "wdssd"
#define ROCKET_STRIKE "wdwa"
#define NAPALM_STRIKE "wdsw"
#define BOMB "wdsss"
#define SMOKE_STRIKE "wdws"

#endif
